using System.IO.Compression;
using System.Reflection;
using System.Text.Json;

namespace AutoKill.Data;

/// <summary>
/// The dense half of the spawn data, generated by tools/data and shipped inside
/// the assembly.
/// </summary>
/// <remarks>
/// LuminaSupplemental knows where to find far more mobs than anything else and
/// very little about each: a median of two recorded points, which is not enough
/// to work out where to stand. This covers fewer mobs and covers them properly,
/// averaging fifteen points and reaching thirty for the ones people farm.
///
/// Positions are map coordinates keyed by BNpcName, deliberately unclustered:
/// clustering belongs after the two sources are merged, not within either.
/// Each row is [mapId, x, y, level], and a level of zero means nobody recorded
/// one rather than the mob being level zero.
/// </remarks>
public static class EmbeddedPositions
{
    private const string ResourceName = "AutoKill.Data.positions.json.gz";

    public sealed record Payload(int Version, Dictionary<uint, List<float[]>> Positions);

    public static Dictionary<uint, List<float[]>> Load()
    {
        using var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(ResourceName)
                           ?? throw new InvalidOperationException($"missing embedded resource {ResourceName}");
        using var gzip = new GZipStream(stream, CompressionMode.Decompress);

        var payload = JsonSerializer.Deserialize<Payload>(gzip, new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true,
        });

        return payload?.Positions ?? [];
    }
}
